mystruct.c File Reference
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include `mystruct.h`
Functions
struct Employee * makeEmployee (int birth, int start, const char *name)
void printEmployee (struct Employee *e)
struct Employee * makeRandomEmployee ()
char * generateRandomChar ()
char * generateRandomString ()
struct Employee ** makeEmployeeArray (int count)
void printEmployeeArray (struct Employee **e, int size)
struct Employee ** shallowCopy (struct Employee **e, int size)
void freeArray (struct Employee **e, int size)
struct Employee * copyEmployee (struct Employee *e)
struct Employee ** deepCopy (struct Employee **e, int size)
Function Documentation
copyEmployee()
struct Employee* copyEmployee (struct Employee * e)
Deep copies the employee e into a new employee, that is to say all the data is the same but all the pointers to the data are different.
Parameters
e the employee to deep copy
Returns
a deep copied version of e
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by deepCopy(), and testCopyEmployee().
deepCopy()
struct Employee** deepCopy (struct Employee ** e, int size)
Deep copies an array of employees into a new array of employees, where all the data is the same but new pointers to all that data.
Parameters
e the employee array to deep copy
size the size of the array
Returns
a deep copied version of e
References copyEmployee().
Referenced by testDeepCopy().
freeArray()
void freeArray (struct Employee ** e, int size)
Frees the interior content of an employee array, as well as e itself.
Parameters
e the array to free
size the size of the array
Returns
none
Referenced by testDeepCopy(), testFreeArray(), testMakeEmployeeArray(), testPrintEmployeeArray(), and testShallowCopy().
generateRandomChar()
char* generateRandomChar ()
Generates a random printable character.
Parameters
none
Returns
the random character
Referenced by generateRandomString(), and testGenerateRandomChar().
generateRandomString()
char* generateRandomString ()
Generates a random string from length of 0 to 20. The string pointer must be freed once the user is done with it.
Parameters
none
Returns
a random string
References generateRandomChar().
Referenced by makeRandomEmployee(), and testGenerateRandomString().
makeEmployee()
struct Employee* makeEmployee (int birth, int start, const char * name)
mystruct.c
Author
Ravi Kirschner Allocates an Employee struct and fills in its fields
Parameters
birth Year the employee was born.
start Year the employee started with the company.
name String containing employee's name
Returns
Pointer to Employee struct, newly allocated from the heap.
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by makeRandomEmployee(), testMakeEmployee(), and testPrintEmployeeArray().
makeEmployeeArray()
struct Employee** makeEmployeeArray (int count)
Generates an array of size count full of random employees. The Employee array must be freed once the user is done with it.
Parameters
count the size of the array
Returns
the array filled with random employees.
References makeRandomEmployee().
Referenced by testDeepCopy(), testFreeArray(), testMakeEmployeeArray(), and testShallowCopy().
makeRandomEmployee()
struct Employee* makeRandomEmployee ()
Generates a random employee
Parameters
nome
Returns
a random employee struct
References generateRandomString(), makeEmployee(), and Employee::name.
Referenced by makeEmployeeArray(), testCopyEmployee(), and testMakeRandomEmployee().
printEmployee()
void printEmployee (struct Employee * e)
A function to print all the fields of an employee struct to the console
Parameters
e the employee to print out
Returns
none
References Employee::birth_year, Employee::name, and Employee::start_year.
Referenced by printEmployeeArray(), testMakeEmployee(), testMakeRandomEmployee(), and testPrintEmployee().
printEmployeeArray()
void printEmployeeArray (struct Employee ** e, int size)
Prints an entire array of employees to the console.
Parameters
e the array of employees to be printed
size the size of the array e
Returns
none
References printEmployee().
Referenced by testMakeEmployeeArray(), and testPrintEmployeeArray().
shallowCopy()
struct Employee** shallowCopy (struct Employee ** e, int size)
Shallow copies an array of employee structs. That is to say, it makes a new array but the pointers inside of it are the same.
Parameters
e the old array of Employees
size the size of the old array
Returns
a new array of Employees with the same data as e but not the same pointers
Referenced by testShallowCopy().