tests.h File Reference
#include <stdbool.h>
#include `production.h`
Functions
bool tests (void)
bool testPrintEmployee (void)
bool testMakeEmployee ()
bool testGenerateRandomChar ()
bool testGenerateRandomString ()
bool testMakeRandomEmployee ()
bool testPrintEmployeeArray ()
bool testMakeEmployeeArray ()
bool testShallowCopy ()
bool testFreeArray ()
bool testCopyEmployee ()
bool testDeepCopy ()
Function Documentation
testCopyEmployee()
bool testCopyEmployee ()
Tests the copyEmployee() function by creating an employee, copying it, and checking pointers
Returns
true if pass, false if fail.
References Employee::birth_year, copyEmployee(), makeRandomEmployee(), Employee::name, and Employee::start_year.
Referenced by tests().
testDeepCopy()
bool testDeepCopy ()
Tests the deepCopy() function by creating an array, deep copying it, and checking pointers
Returns
true if pass, false if fail
References deepCopy(), freeArray(), makeEmployeeArray(), and Employee::name.
Referenced by tests().
testFreeArray()
bool testFreeArray ()
Tests the freeArray() function by making an array and freeing it
Returns
true. As long as the function doesn't crash the program, it passes.
References freeArray(), and makeEmployeeArray().
Referenced by tests().
testGenerateRandomChar()
bool testGenerateRandomChar ()
Tests the generateRandomChar() function by making and printing a character.
Returns
true. The only way to tell if it succeeds is to look at the output
References generateRandomChar().
Referenced by tests().
testGenerateRandomString()
bool testGenerateRandomString ()
Tests the generateRandomString() function by making and printing a string.
Returns
true. The only way to tell if it succeeds is to look at the output
References generateRandomString().
Referenced by tests().
testMakeEmployee()
bool testMakeEmployee ()
Test the make Employee() function by making an employee with known data and printing it.
Returns
true. The only way to tell if it succeeds is to look at the output.
References makeEmployee(), and printEmployee().
Referenced by tests().
testMakeEmployeeArray()
bool testMakeEmployeeArray ()
Tests the makeEmployeeArray() function by calling it and printing the results.
Returns
true. The only way to tell if it succeeds is to look at the output
References freeArray(), makeEmployeeArray(), and printEmployeeArray().
Referenced by tests().
testMakeRandomEmployee()
bool testMakeRandomEmployee ()
Tests the makeRandomEmployee() function by generating and printing that employee.
Returns
true. The only way to tell if it succeeds is to look at the output
References makeRandomEmployee(), and printEmployee().
Referenced by tests().
testPrintEmployee()
bool testPrintEmployee (void)
Test the printEmployee() function by creating a known struct and printing it.
Returns
true. The only way to tell if it succeeds is to look at the output.
References Employee::birth_year, MAX_NAME, Employee::name, printEmployee(), and Employee::start_year.
Referenced by tests().
testPrintEmployeeArray()
bool testPrintEmployeeArray ()
Tests the printEmployeeArray() function by generating an array of employees and printing it
Returns
true. The only way to tell if it succeeds is to look at the output
References freeArray(), makeEmployee(), and printEmployeeArray().
Referenced by tests().
tests()
bool tests (void)
References testCopyEmployee(), testDeepCopy(), testFreeArray(), testGenerateRandomChar(), testGenerateRandomString(), testMakeEmployee(), testMakeEmployeeArray(), testMakeRandomEmployee(), testPrintEmployee(), testPrintEmployeeArray(), and testShallowCopy().
Referenced by main().
testShallowCopy()
bool testShallowCopy ()
Tests the shallowCopy() function by making an array and shallow copying it. To make sure it is okay, we check if the pointers to the arrays themselves are not the same, but we check to see if the pointers within the array are the same.
Returns
true if succeed, false if fair
References freeArray(), makeEmployeeArray(), and shallowCopy().
Referenced by tests().