mystring.h File Reference
#include <string.h>
Functions
size_t mystrlen1 (const char *s)
size_t mystrlen2 (const char *s)
char * mystrdup (char *s)
char * mystrndup (char *s, size_t n)
char * mystrcpy (char *dest, char *src)
char * mystrncpy (char *dest, char *src, size_t n)
char * mystrncat (char *dest, char *src, size_t n)
char * mystrcat (char *dest, char *src)
Function Documentation
mystrcat()
char* mystrcat (char * dest, char * src)
Concatenates a copy of the string pointed to by src onto the end of the string pointed to by dest. Overwrites the null character at the end of dest, and adds a null terminator at the end of the new string. Will concatenate even if there is not enough space in dest.
Parameters
dest the destination to concatenate onto
src the string to concatenate onto dest.
Returns
a pointer to dest
References mystrcpy(), and mystrlen2().
Referenced by mystrncat(), and testMystrcat().
mystrcpy()
char* mystrcpy (char * dest, char * src)
Copies a string src into the address dest. Overwrites anything at dest. Src and dest should have the same size, that is if src is 10 characters, dest should be as well.
Parameters
char* the destination to copy into
char* the source location to copy from
Returns
the start of the newly copied to string, or just dest
Referenced by mystrcat(), testMystrcpy(), and testMystrncat().
mystrdup()
char* mystrdup (char * s)
Duplicates a character string into a freshly-allocated block of memory.
Parameters
s The string to duplicate.
Returns
Pointer to the new string. NULL if unable to allocate memory, errno holds the error code.
Referenced by testMystrdup().
mystrlen1()
size_t mystrlen1 (const char * s)
Calculate the length of the string, excluding the terminating null byte ('\0')
Parameters
const char* s
Returns
number of characters in the string pointed to by s
Referenced by testMystrlen1().
mystrlen2()
size_t mystrlen2 (const char * s)
Calculate the length of the string excluding the terminating null byte ('\0')
Parameters
const char* s
Returns
number of characters in the string pointed to by s
Referenced by mystrcat(), mystrncat(), and testMystrlen2().
mystrncat()
char* mystrncat (char * dest, char * src, size_t n)
Appends the first n characters of src to the string pointed to by dest, plus a null terminator. If n is greater than the length of *src, then it just appends over the entirety of src. If n is equal to the length of src, it simply appends over the entirety of src. If n is less than the length of src, only the first n characters of src (and a null terminator) will be appended to dest.
Parameters
dest the destination to concatenate onto
src the source to concatenate from
n the amount of characters to concatenate over from src
Returns
pointer to dest
References mystrcat(), and mystrlen2().
Referenced by testMystrncat().
mystrncpy()
char* mystrncpy (char * dest, char * src, size_t n)
Copies the first n characters of src to the string pointed to by dest As this function copies AT MOST n bytes from src, the function does not null terminate if n < src. Else if n is greater than strlen(src), the function will write null terminators until n bytes of data are written into dest.
Parameters
dest the destination to copy into
src the src to copy from
n the amount of bytes to copy
Returns
pointer to dest
Referenced by testMystrncpy().
mystrndup()
char* mystrndup (char * s, size_t n)
Duplicates the first n characters of a string into a newly allocated block of memory. If n is less than the size of src, the first n characters of src will be duplicated and a null terminator will be added.
Parameters
s the string to duplicate
n the number of characters to duplicate
Returns
a pointer to the newly duplicated string
Referenced by testMystrndup().